# This project uses the GitFlow Workflow as defined here:
#   https://www.atlassian.com/git/tutorials/comparing-workflows#GitFlow-workflow
image: ericlineback/hspc-base

pipelines:
  default:
    - step:
        script:
          - echo "Please use a GitFlow branch"
          - exit 1;
  branches:
    develop:
      - step:
          caches:
            - maven
          script:
            # Deploy to hspc-nexus
            - mvn -V -B -s settings.xml deploy -P DEPLOY-HSPC,hspc-nexus
            # install ASW CLI and jq library
#            - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
#            - unzip awscli-bundle.zip
#            - ./awscli-bundle/install -b ~/bin/aws
#            - export PATH=~/bin:$PATH
#            - curl -o /usr/local/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /usr/local/bin/jq
            # clear out the other jar files
            - rm reference-auth-server-webapp/target/*-sources.jar
            - rm reference-auth-server-webapp/target/*-javadoc.jar
            # build docker image and push to nexus.interopion.com:18083 (docker-interopion)
            - export IMAGE_NAME=$(cat container-definitions_test.json | jq --raw-output '.[0].image')
            - docker login -u $NEXUS_USR -p $NEXUS_PWD nexus.hspconsortium.org:18083
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME
            # Add jasypt pw to container definition
            - jq '.[].environment += [{"name":"JASYPT_ENCRYPTOR_PASSWORD", "value":"'$ENC_PW_TEST'"}]' container-definitions_test.json > tmp.json && mv tmp.json container-definitions_test.json
            # register the ECS task definition and capture the version
            - export TASK_VERSION=$(aws ecs register-task-definition --family hspc-reference-auth --container-definitions $(cat container-definitions_test.json | jq -c '.')  | jq --raw-output '.taskDefinition.revision')
            - echo "Registered ECS Task Definition - " $TASK_VERSION
            # update the service to use the latest task definition
            - aws ecs update-service --cluster hspc-test --service hspc-reference-auth-service --task-definition hspc-reference-auth:$TASK_VERSION
    feature/*:
      - step:
          caches:
            - maven
          script:
            - mvn -B verify
    release/*:
      - step:
          caches:
            - maven
          script:
            - mvn -B verify
    hotfix/*:
      - step:
          caches:
            - maven
          script:
            - mvn -B verify
    master:
      - step:
          script:
            # Deploy to maven central
            - openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in private-key.gpg.enc -out private-key.gpg -d
            - gpg --batch --import private-key.gpg
#            - mvn -V -B -s settings.xml deploy -P DEPLOY,ossrh
            # Deploy to hspc-nexus
            - mvn -V -B -s settings.xml deploy -P DEPLOY-HSPC,hspc-nexus
            # install ASW CLI and jq library
#            - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
#            - unzip awscli-bundle.zip
#            - ./awscli-bundle/install -b ~/bin/aws
#            - export PATH=~/bin:$PATH
#            - curl -o /usr/local/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /usr/local/bin/jq
            # clear out the other jar files
            - rm reference-auth-server-webapp/target/*-sources.jar
            - rm reference-auth-server-webapp/target/*-javadoc.jar
            # build docker image and push to nexus.interopion.com:18083 (docker-interopion)
            - export IMAGE_NAME=$(cat container-definitions_test.json | jq --raw-output '.[0].image')
            - docker login -u $NEXUS_USR -p $NEXUS_PWD nexus.hspconsortium.org:18083
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME
options:
  docker: true